version: '3.9'

services:
  mysql:
    image: mysql:8.0.36
    container_name: alles-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 20s
      retries: 5
    networks:
      - alles-network

  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: spring-app
      restart: always
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ports:
        - "8080:8080"
      networks:
        - alles-network

#  phpmyadmin:
#    image: phpmyadmin:latest
#    container_name: alles-phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_USER: root
#      PMA_PASSWORD: root
#      PMA_DATABASE: alles
#    ports:
#      - "8081:80"
#    depends_on:
#      - mysql
#    networks:
#      - alles-network

volumes:
  mysql_data:
    driver: local

networks:
  alles-network:
    driver: bridge
